# Step 1: Build Java artifact using Maven
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY backend/pom.xml .
COPY backend/src ./src
RUN mvn clean package -DskipTests

# Step 2: Runtime Container with OpenJDK 21
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/expense-tracker-backend-1.0.0.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=prod"]
